const ENVIRONMENTS = {
  DEVELOPMENT: "development",
  STAGING: "staging",
  PRODUCTION: "production",
};

const APP_LOG_MESSAGE = {
  APP_STARTED: "🚀 APPLICATION STARTED",
  APP_ERROR: "❌ APPLICATION ERROR",
  DB_CONNECTED: `✅ DATABASE CONNECTED`,
  DB_CONNECTION_ERROR: "❌ DB CONNECTION ERROR",
  MISSING_ENV_VARIABLE: "⚠️ MISSING ENVIRONMENT VARIABLE",
  VALIDATION_ERROR: "❌ VALIDATION ERROR",
};

export { ENVIRONMENTS, APP_LOG_MESSAGE };
